language: cpp
os:
  - linux
  - osx
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxi-dev
script:
  - clang++ -v
  - cd src && ./externals.sh
  - ./gmake.sh
  - cd build && make
